== イントロダクション

まず最初に…、tarling コミュニティーへようこそ！
2011年の最初のリリース以来、世界中のデベロッパーがこの小さな赤い鳥とともに、素晴らしいゲームやアプリを開発してきました。
このドキュメントを読んでくれているあなたが仲間入りしてくれる事はとても素晴らしい事です。

//原文：You have come to the right place:
あなたは正しいドキュメントを手にしています。
このマニュアルはあなたが知るべきことを全て教えてくれます。
AからZまで、例えばA…、_Asset Management_ から、Z…(えーと) _Zen-like coding_ までです。

まず、フレームワークの雰囲気を掴んでもらうために、１から小さなゲームを作っていきましょう。
その後、ディスプレイリストの構成やアニメーションシステムのコンセプトについて詳細まで見ていきます。
//原文：Later chapters contain information for advanced Starling users, like how to write custom rendering code.
その後の章では、中上級 Starling ユーザの為に、（シェーダーを用いた）カスタムレンダリングの書き方などについて言及します。
//原文：Before you know it, you'll be a master of Starling!
そうこうしているうちに、あなたは Starling マスターとなっている事でしょう！

その為には _ActionScript 3_ (AS3)の基本的な理解をしていなくてはいけません。
//原文：Fear not: if you have used any other object oriented language, you will get the hang of it quickly.
しかし、心配はいらないかもしれません。何かしらオブジェクト指向言語の経験があればすぐに AS3 の理解は深める事ができるでしょう。
//原文：There are numerous books and tutorials available that will get you started.
世の中にある、たくさんの本やチュートリアルも役に立つはずです。

あえて述べるならば、_Colin Moock_ 氏の著書である "Essential ActionScript 3" をオススメします。私自身もこの本にお世話になり、たくさんの重要なことを学びました。そして今でもしばしば本棚からこの本を取り出してくるのです。
（特にAS3の奇妙な仕様のXMLの取り扱い方法、E4X、について調べる時などに。）

.AS3 vs. JS
****
_ActionScript 3_ が実際には _JavaScript_ の後継言語としてデザインされているのを知っていましたか？
ご存知の通り、_JavaScript_ は _ECMAScript_ 仕様の実装であり、_ActionScript 3_ は _ECMAScript 4_ に基づいています。
しかし主に政治的な理由により、_ECMAScript 4_ は見捨てられ、ブラウザに実装される事はありませんでした。
今日では、_ActionScript 3_ は _ECMAScript 4_ の唯一の標準実装となっています。
皮肉な事に、最近の _JavaScript_ はどんどんと _ActionScript 3_ に似てきています。
****
