== リソース一覧

//原文：We almost have all the building blocks in place now.
必要な道具はほぼ揃いました。
//原文：Let's see how to set everything up so that we can finally get started with our first project, right?
最初のプロジェクトを始めるため、どのように準備をすればいいか見てみましょう。

=== AIR SDK

IDE の準備が終わったならば、次にすることは _AIR SDK_ 最新バージョンのダウンロードです。
Adobe は SDK の安定バージョンを３ヶ月に１度定期リリースします。常に最新をキープしましょう。
新しいリリースにはたいてい重要なバグフィックスが含まれ、それは最新のモバイルOSとの互換性を保つのに重要なものです。
//原文：You will also constantly see the team experimenting with new features,
さらに、新機能の実験的な実装などもしばしば見ることでできるでしょう。
//原文：and I'm trying hard to keep up with that pace in Starling.
なるべくこの SDK の 更新ペースについていけるよう、Starling への取り込みも頑張っています。

最新のリリースバージョンはいつでもここで見つけることができます。
https://www.adobe.com/devnet/air/air-sdk-download.html[Download Adobe AIR SDK]

NOTE: Starling のバージョン2系 は AIR のバージョン19以上を必要とします。

=== Flash Player プロジェクター

もしもあなたのプロジェクトが _Flash Player_ 上でも動くコンテンツを作ることも目的とするなら、
_Flash Player_ の スタンドアロン版を手に入れることをオススメします。
_プロジェクター_ と呼ばれるものです。（プロジェクターには、_デバッグ版_ と _リリース版_ が存在します。）

プロジェクターを使うとデバッグ開発を行うのが簡単になります。
もちろんデバッグ版の Flash Player をブラウザにインストールしてデバッグを行うこともできます。しかし個人的にはとても面倒に感じます。

プロジェクターはずっと速く起動しますし、動作させるために html ファイルを用意する必要もありません。

下記のページは開発者が利用可能な全てのバージョンの Flash Player を含んでいます。
"projector content debugger" という項目を探してください。

https://www.adobe.com/support/flashplayer/debug_downloads.html[Adobe Flash Player Debug Downloads]

NOTE: デバッグ版の動作は通常盤に比べて著しく低速です。コンテンツのパフォーマンス調整を行う際はこの事に気をつけてください。

あなたが使っている IDE はどのバージョンの Player を使えばいいか設定してやる必要があるかもしれません。
例えば、_IDEA_ ではデバッグ設定スクリーンに、この Player 設定が存在します。
他の IDE では シンプルに OS のシステム設定の Player を使うかも知れません。
どの場合でも、SWF ファイルをコンパイルする AIR SDK のバージョンと同じか高いバージョンの Player を使う事が必要です。

=== Starling

さて、あと残すは Starling 自体のダウンロードだけです。
２つの方法で手に入れる事ができます。

a. 最新のリリースを ZIP ファイルで入手：http://gamua.com/starling/download/[gamua.com/starling/download]
b. Starling の _Git_ リポジトリをクローンする

前者の良い点は、ライブラリをコンパイル済みの SWC ファイルが付属してくる事です。(`starling/bin` フォルダ以下に配置されています。)
SWC ファイルは簡単にプロジェクトに取り込む事ができます。

しかし、この方法では安定リリースバージョンしか手に入れる事ができません。
最新機能やバグ修正をすぐさま取り入れることはできないのです。
この理由から、_Git_ を使ってファイルを入手することをオススメします。

TIP: あなたがバグレポートをしたとして、数日後にすぐそれが修正されたとします。（そういうことは実際にあります。）
通常のダウンロードの方法では、次の安定バージョンのリリースを私が作るまで、かなり長い間待つ場合がありますが、
もしも _Git_ リポジトリを使っているならば、すぐさま修正バージョンを手に入れることができるのです。

_Git_ について詳しい解説をすると、このマニュアルの範疇を超えてしまいます。
しかし、web 上には Git の良いチュートリアルがたくさん見つかるはずです。
一度 GIT をインストールすれば、下記のコマンドにより、Starling リポジトリの完全なコピーをあなたの PC 上に手に入れることができます。

  git clone https://github.com/Gamua/Starling-Framework.git

このお万度により、`Starling-Framework` フォルダの下に Starling のコピーが作られます。

ライブラリの実際のソースコードは `starling/src` というサブフォルダの中に見つかります。
先の述べた全ての IDE が _source path_ として、このソースコードフォルダを登録できます。
これにより、Starling をあなたのプロジェクトの一部として取り込むことができます。
SWC ファイルをリンクすることより難しいなんていうことはありません。
//原文：and as a neat side effect, you will even be able to step into Starling's source on debugging.
そして素敵な副次作用として、デバッグ開発時には Starling のソースコードに直接潜っていって参照することができます。

そして、このアプローチの最も良い部分は、簡単に最新バージョンの Starling に更新することができることです。

単純に、リポジトリのディレクトリにて`pull`コマンドを実行してください。

  cd Starling-Framework
  git pull

この方法はブラウザを開いて最新ファイルをダウンロードするより、ずっとシンプルです。そう思いませんか？

[NOTE]
====
_Git_ ユーザ向けにいくつか追加の情報を記します。

//原文：* All day-to-day development in Starling happens on the `master` branch.
* 日々の Starling の開発は `master` ブランチで行われます。
* 安定バージョンは _タグ付け_ されます。 (例えば `v2.0`, `v2.0.1`, `v2.1` など)
* それぞれのタグは _GitHub_ 上で _Release_ として扱われ、そこにはコンパイル済みの SWC ファイルも付属されます。
====

=== Getting Help

//原文：The best of us get stuck sometimes.
誰にでも行き詰ってしまうことはあります。
//原文：You might hit a road block because of a bug in Starling, or maybe because of a problem that seems impossible to solve.
解決不可能な問題に直面したり、Starling のバグのせいで先に進めなくなる事もあるでしょう。

どちらにしても、Starling コミュニティ はあなたを一人置き去りにはしません。

ヘルプが必要な時に訪れるべき情報源となるサイトがいくつか存在します。

Starling フォーラム::
Starling コミュニティの中の一番のハブたる場所です。
毎日たくさんの投稿があり、あなたが持っている問題はすでにここで質問済みであることも多いでしょう。
_検索_ 機能を活用してください。

もしも目的の情報がみつからないのなら、メンバー登録をして気軽に質問をしてください。
web上で最も親切で寛容なコミュニティをそこに見つける事ができるでしょう。 +
-> http://forum.starling-framework.org


Starling マニュアル::
ifdef::target-manual[今あなたが読んでいるこのページの事です.]
ifndef::target-manual[オンラインマニュアルは広い範囲の Starling の解説を提供します。]
できる限り Straling のリリースと共にこのマニュアルも更新していくつもりです。 +
-> http://manual.starling-framework.org

Starling Wiki::
//原文：The wiki contains links and articles about different Starling related topics,
wiki ページは また他と異なった感じで Starling に関する話題のリンクや記事を含んでいます。
そしてこれは重要なコンテンツかと思うのですが、Starling の拡張機能の一覧ページを持っています。
いくつかの拡張機能については後ほどまた紹介します。 +
-> http://wiki.starling-framework.org

API リファレンス::
Starling の API リファレンス ページを参照するのも忘れないでください。
クラスやメソッドについてより詳細な情報が得られます。 +
-> http://doc.starling-framework.org

Gamua Blog::
Gamua blog で Starling について、最新の情報を手に入れてください。
正直なところ、ブログを書くのは怠けてしまう事もあるのですが、
Starling の最新リリースについての情報は必ずブログに投稿されています。 +
-> http://gamua.com/blog

Twitter::
私は いくつかの SNS を使っていますが、Twitter で `@Gamua` とメンションするのが、私と連絡を取る一番良い方法です。
このアカウントをフォローして、新しい開発内容や、Starling で作られたゲームなどの最新情報を手に入れてください。 +
-> https://twitter.com/Gamua

